In [2]:
import pandas as pd
df = pd.read_csv("C:/Users/SAKTHI NARAYANA RAO/Downloads/ipl_match_dataset.csv")
df.head()

,id,season_year,city,venue,match_type,team1,team2,toss_winner_is_team1,bat_first,inn1_runs,...,inn1_sixes,inn2_runs,inn2_wickets,inn2_balls,inn2_extras,inn2_fours,inn2_sixes,top_score,top_wickets,team1_won
0,335982,2007,Bangalore,M Chinnaswamy Stadium,League,Royal Challengers Bangalore,Kolkata Knight Riders,1,0,222,...,14,82.0,10.0,101.0,19.0,3.0,3.0,158,3,0.0
1,335983,2007,Chandigarh,"Punjab Cricket Association Stadium, Mohali",League,Kings XI Punjab,Chennai Super Kings,0,1,240,...,16,207.0,4.0,124.0,11.0,18.0,9.0,116,2,0.0
2,335984,2007,Delhi,Feroz Shah Kotla,League,Delhi Daredevils,Rajasthan Royals,0,1,129,...,3,132.0,1.0,97.0,10.0,18.0,1.0,58,3,1.0
3,335985,2007,Mumbai,Wankhede Stadium,League,Mumbai Indians,Royal Challengers Bangalore,1,1,165,...,5,166.0,5.0,123.0,5.0,15.0,6.0,48,4,0.0
4,335986,2007,Kolkata,Eden Gardens,League,Kolkata Knight Riders,Deccan Chargers,0,1,110,...,6,112.0,5.0,122.0,28.0,5.0,4.0,38,4,1.0

In [3]:
df.isnull().sum()

id                       0
season_year              0
city                    51
venue                    0
match_type               0
team1                    0
team2                    0
toss_winner_is_team1     0
bat_first                0
inn1_runs                0
inn1_wickets             0
inn1_balls               0
inn1_extras              0
inn1_fours               0
inn1_sixes               0
inn2_runs                0
inn2_wickets             0
inn2_balls               0
inn2_extras              0
inn2_fours               0
inn2_sixes               0
top_score                0
top_wickets              0
team1_won                0
dtype: int64

In [4]:
df.drop("id",axis=1,inplace=True)
df.drop("inn1_runs",axis=1,inplace=True)
df.drop("inn2_runs",axis=1,inplace=True)
df.drop("top_score",axis=1,inplace=True)
df.drop("top_wickets",axis=1,inplace=True)
df.drop("inn1_wickets",axis=1,inplace=True)
df.drop("inn1_balls",axis=1,inplace=True)
df.drop("inn1_extras",axis=1,inplace=True)
df.drop("inn1_fours",axis=1,inplace=True)
df.drop("inn1_sixes",axis=1,inplace=True)
df.drop("inn2_wickets",axis=1,inplace=True)
df.drop("inn2_balls",axis=1,inplace=True)
df.drop("inn2_extras",axis=1,inplace=True)
df.drop("inn2_fours",axis=1,inplace=True)
df.drop("inn2_sixes",axis=1,inplace=True)

In [5]:
X = df.drop(columns=["team1_won"])
y = df["team1_won"]

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [7]:
df.head(2)

,season_year,city,venue,match_type,team1,team2,toss_winner_is_team1,bat_first,team1_won
0,2007,Bangalore,M Chinnaswamy Stadium,League,Royal Challengers Bangalore,Kolkata Knight Riders,1,0,0.0
1,2007,Chandigarh,"Punjab Cricket Association Stadium, Mohali",League,Kings XI Punjab,Chennai Super Kings,0,1,0.0

In [8]:
X_train

,season_year,city,venue,match_type,team1,team2,toss_winner_is_team1,bat_first
352,2013,Delhi,Feroz Shah Kotla,League,Delhi Daredevils,Kings XI Punjab,0,0
636,2018,Hyderabad,Rajiv Gandhi International Stadium,League,Rajasthan Royals,Sunrisers Hyderabad,0,0
1036,2024,Hyderabad,"Rajiv Gandhi International Stadium, Uppal, Hyd...",League,Chennai Super Kings,Sunrisers Hyderabad,0,0
249,2012,Mumbai,Wankhede Stadium,League,Mumbai Indians,Pune Warriors,1,0
622,2017,Kanpur,Green Park,League,Gujarat Lions,Delhi Daredevils,0,0
...,...,...,...,...,...,...,...,...
330,2013,Bangalore,M Chinnaswamy Stadium,League,Royal Challengers Bangalore,Sunrisers Hyderabad,0,1
466,2015,Pune,Maharashtra Cricket Association Stadium,League,Kings XI Punjab,Delhi Daredevils,1,1
121,2009,Bangalore,M Chinnaswamy Stadium,League,Royal Challengers Bangalore,Kings XI Punjab,0,1
1044,2024,Lucknow,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,League,Lucknow Super Giants,Delhi Capitals,1,1
860,2021,Dubai,Dubai International Cricket Stadium,League,Sunrisers Hyderabad,Kolkata Knight Riders,1,1

In [9]:
df['city'] = df['city'].fillna('Unknown')
df['city'] = df['city'].fillna('Unknown')

In [10]:
from sklearn.preprocessing import LabelEncoder
categorical_col = [
    'city',
    'venue',
    'match_type',
    'team1',
    'team2',
]

encoders = {}

for col in categorical_col:
    le = LabelEncoder()

    X_train[col] = le.fit_transform(X_train[col])
    X_test[col] = le.transform(X_test[col])

    encoders[col] = le

In [11]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train,y_train)

RandomForestClassifier()

In [12]:
y_pred = model.predict(X_test)
y_pred

array([0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 0., 0.,
       0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1.,
       0., 0., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0.,
       0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0.,
       1., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1.,
       1., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1.,
       0., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.,
       1., 1., 1., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0., 1., 0.,
       0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0.,
       1., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
       0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1.,
       0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0.,
       0., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 0., 1.])

In [13]:
from sklearn.metrics import accuracy_score
print("ACCURACY :",accuracy_score(y_test,y_pred))

ACCURACY : 0.5045871559633027

In [15]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import cross_val_score
import numpy as np

# 1. Create the encoder
# handle_unknown='use_encoded_value' prevents errors if a new city appears
encoder = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)

# 2. Make a copy of X to keep your original data safe
X_encoded = X.copy()

# 3. Transform the categorical columns in the WHOLE dataset X
X_encoded[categorical_col] = encoder.fit_transform(X[categorical_col])

# 4. Now use X_encoded in your cross-validation
cross = cross_val_score(model, X_encoded, y, cv=5)

print(f"Average CV Accuracy: {np.mean(cross):.4f}")

Average CV Accuracy: 0.4817

In [33]:
df.describe()

       season_year  toss_winner_is_team1    bat_first    team1_won
count  1090.000000           1090.000000  1090.000000  1090.000000
mean   2016.015596              0.388073     0.357798     0.509174
std       5.113113              0.487535     0.479572     0.500145
min    2007.000000              0.000000     0.000000     0.000000
25%    2012.000000              0.000000     0.000000     0.000000
50%    2016.000000              0.000000     0.000000     1.000000
75%    2021.000000              1.000000     1.000000     1.000000
max    2024.000000              1.000000     1.000000     1.000000

OUTLIER DETECTION

In [36]:
import pickle

pickle.dump(model, open("model.pkl", "wb"))

In [37]:
pickle.dump(encoders, open("encoders.pkl", "wb"))

In [38]:
print(df["team1"].unique())
print(df["city"].unique())
print(df["match_type"].unique())

['Royal Challengers Bangalore' 'Kings XI Punjab' 'Delhi Daredevils'
 'Mumbai Indians' 'Kolkata Knight Riders' 'Rajasthan Royals'
 'Deccan Chargers' 'Chennai Super Kings' 'Kochi Tuskers Kerala'
 'Pune Warriors' 'Sunrisers Hyderabad' 'Gujarat Lions'
 'Rising Pune Supergiants' 'Rising Pune Supergiant' 'Delhi Capitals'
 'Punjab Kings' 'Lucknow Super Giants' 'Gujarat Titans'
 'Royal Challengers Bengaluru']
['Bangalore' 'Chandigarh' 'Delhi' 'Mumbai' 'Kolkata' 'Jaipur' 'Hyderabad'
 'Chennai' 'Cape Town' 'Port Elizabeth' 'Durban' 'Centurion' 'East London'
 'Johannesburg' 'Kimberley' 'Bloemfontein' 'Ahmedabad' 'Cuttack' 'Nagpur'
 'Dharamsala' 'Kochi' 'Indore' 'Visakhapatnam' 'Pune' 'Raipur' 'Ranchi'
 'Abu Dhabi' 'Unknown' 'Rajkot' 'Kanpur' 'Bengaluru' 'Dubai' 'Sharjah'
 'Navi Mumbai' 'Lucknow' 'Guwahati' 'Mohali']
['League' 'Semi Final' 'Final' '3rd Place Play-Off' 'Qualifier 1'
 'Elimination Final' 'Qualifier 2' 'Eliminator']